<?php

/**
 * @file
 * BC Admin pages.
 */
define('BC_ADMIN_SLIDE_FRAME_SVG', 'bc_admin_slide_frame');
define('BC_ADMIN_SLIDE_FRAME_FALLBACK', 'bc_admin_slide_frame_fallback');
define('BC_ADMIN_SLIDE_CONTROL_LEFT', 'bc_admin_slide_left');
define('BC_ADMIN_SLIDE_CONTROL_LEFT_FALLBACK', 'bc_admin_slide_left_fallback');
define('BC_ADMIN_SLIDE_CONTROL_RIGHT', 'bc_admin_slide_right');
define('BC_ADMIN_SLIDE_CONTROL_RIGHT_FALLBACK', 'bc_admin_slide_right_fallback');

/**
 * Implements hook_entity_info_alter().
 */
function bc_admin_menu() {
  $items['admin/config/baladecoco'] = array(
    'title' => 'BC Config',
    'description' => 'Add several configuration options to the website.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_bc_admin_main_form'),
    'access callback' => TRUE,
    'weight' => 0,
    'file' => 'bc_admin.admin.inc',
  );

  $items['admin/config/baladecoco/default'] = array(
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'title' => 'BC Config',
    'weight' => 1,
  );
  
  $menus = array(
    array(
      'name' => 'slider',
      'title' => t('Slider Frame'),
      'callback' => '_bc_admin_slider_form',
    ), 
    array(
      'name' => 'todo',
      'title' => t('TODO'),
      'callback' => '_bc_admin_main_form',
    )
  );
  foreach ($menus as $weight => $menu) {
    $items["admin/config/baladecoco/{$menu['name']}"] = array(
      'type' => MENU_LOCAL_TASK,
      'title' => $menu['title'],
      'page callback' => 'drupal_get_form',
      'page arguments' => array($menu['callback']),
      'access callback' => TRUE,
      'weight' => $weight,
      'file' => 'bc_admin.admin.inc',
    );
  }

  return $items;
}
