<?php

/**
 * @file
 * Maintains panel panes.
 */

/**
 * Implements hook_ctools_plugin_directory().
 */
function bc_panes_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && !empty($plugin_type)) {
    return 'plugins/' . $plugin_type;
  }
}

/**
 * Implements hook_theme().
 */
function bc_panes_theme() {
  $theme = array(
    'baladecoco_footer_theme' => array(
      'variables' => array(
        'title' => '',
        'image' => '',
        'contextual_links' => '',
      ),
      'template' => 'baladecoco-footer',
      'path' => drupal_get_path('module', 'baladecoco_panes') . '/plugins/baladecoco_footer',
    ),
  );
  return $theme;
}
