<?php

/**
 * @file
 * Main file for bc_blocks module.
 */

/**
 * Implements HOOK_block_info().
 */
function bc_blocks_block_info() {
  $blocks['bc_contact'] = array(
    'info' => t('BC Contact'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  return $blocks;
}

/**
 * Implements HOOK_block_configure().
 */
function bc_blocks_block_configure($delta = '') {
  $form = array();
  if ($delta == 'bc_contact') {
    $form['bc_contact_link'] = array(
      '#type' => 'textfield',
      '#title' => t('Link'),
      '#default_value' => variable_get('bc_contact_link', '/contact'),
    );
    $form['bc_contact_email'] = array(
      '#type' => 'textfield',
      '#title' => t('Email'),
      '#default_value' => variable_get('bc_contact_email', 'xxxxxxxxxxxxxxx@xxxxx.xxx'),
    );
    $form['bc_contact_phone'] = array(
      '#type' => 'textfield',
      '#title' => t('Phone'),
      '#default_value' => variable_get('bc_contact_phone', '(XX) XXXX-XXXX'),
    );
  }
  return $form;
}

/**
 * Implements HOOK_block_save().
 */
function bc_blocks_block_save($delta = '', $edit = array()) {
  if ($delta == 'bc_contact') {
    variable_set('bc_contact_link', $edit['bc_contact_link']);
    variable_set('bc_contact_email', $edit['bc_contact_email']);
    variable_set('bc_contact_phone', $edit['bc_contact_phone']);
  }
}

/**
 * Implements HOOK_block_view().
 */
function bc_blocks_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'bc_contact':
      $link = variable_get('bc_contact_link', 0);
      $email = array(
        'text' => variable_get('bc_contact_email', 0),
        'icon' => bc_get_icon('mail2', 15),
      );
      $phone = array(
        'text' => variable_get('bc_contact_phone', 0),
        'icon' => bc_get_icon('phone', 15),
      );
      $block['subject'] = t('BC Contact');
      $block['content'] = theme('bc_blocks_contact', array(
        'link' => $link,
        'email' => $email,
        'phone' => $phone
      ));
      break;
  }
  return $block;
}

/**
 * Implements HOOOK_theme().
 */
function bc_blocks_theme($existing, $type, $theme, $path) {
  return array(
    'bc_blocks_contact' => array(
      'variables' => array('link' => '', 'email' => array(), 'phone' => array()),
      'template' => 'templates/bc-blocks--contact',
    ),
  );
}
