<?php

/**
 * @file
 * CT Bala module alter.
 */
define('BC_BALA_SLIDER_WIDTH', 500);
define('BC_BALA_SLIDER_HEIGHT', 360);

/**
 * Implements hook_entity_info_alter().
 */
function bc_bala_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['slideshow'] = array(
    'label' => t('Slideshow'),
    'custom settings' => TRUE,
  );
}

/**
* Implements hook_preprocess_node().
*/
function bc_bala_preprocess_node(&$vars) {
  if($vars['view_mode'] == 'slideshow') {
    $vars['theme_hook_suggestions'][] = 'node__' . $vars['type'] . '__slideshow';
	$vars['image'] = theme('image_style', array(
	  'style_name' => 'slideshow',
	  'path' => $vars['field_bala_image'][LANGUAGE_NONE][0]['uri'],
	  'width' => BC_BALA_SLIDER_WIDTH,
	  'height' => BC_BALA_SLIDER_HEIGHT,
	));
  }
} 

/**
* Implements hook_image_default_styles().
*/
function bc_bala_image_default_styles() {
  $styles = array();
  $styles['slideshow'] = array(
    'label' => t('Slideshow'),
    'effects' => array(
      array(
        'name' => 'image_scale_and_crop',
        'data' => array(
          'height' => BC_BALA_SLIDER_HEIGHT,
          'width' => BC_BALA_SLIDER_WIDTH,
        ),
        'weight' => 0,
      ),
    ),
  );
  return $styles;
}
