---
# Acquia Cloud uses Ubuntu 12.04 LTS.
vagrant_box: geerlingguy/ubuntu1204

# Acquia Cloud defaults to PHP 5.6.
php_version: "5.6"

# Acquia Cloud Search defaults to Solr 4.x.
solr_version: "4.5.1"
installed_extras:
  - drush
  - solr
