<?php
/**
 * @file
 * bc_product_feature.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function bc_product_feature_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Comum',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '06ed688b-4fae-4be8-bc6b-68634b6cb6f4',
    'vocabulary_machine_name' => 'bala_type',
  );
  $terms[] = array(
    'name' => 'Coco',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '43efd7a2-c9eb-4af2-919b-297c9f94fcac',
    'vocabulary_machine_name' => 'flavours',
  );
  $terms[] = array(
    'name' => 'Bombom',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '4f4f9f15-bd61-4710-9295-10bbeb2efed8',
    'vocabulary_machine_name' => 'bala_type',
  );
  $terms[] = array(
    'name' => 'Abacaxi',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '59282bb6-628d-4b14-96b3-3153dc65a4cf',
    'vocabulary_machine_name' => 'flavours',
  );
  $terms[] = array(
    'name' => 'Chocolate',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '5d7b9962-8040-4f95-a45e-3bc0c99d294d',
    'vocabulary_machine_name' => 'flavours',
  );
  $terms[] = array(
    'name' => 'Queijo',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '877efeb9-d46a-4ec5-9ce7-4d6672eb9c04',
    'vocabulary_machine_name' => 'flavours',
  );
  $terms[] = array(
    'name' => 'Brigadeiro',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'a7d484bb-feed-4c0f-9bff-784b6b1fdffc',
    'vocabulary_machine_name' => 'product_type',
  );
  $terms[] = array(
    'name' => 'Goiaba',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'a9923934-b10d-4f99-977d-9285960ee06b',
    'vocabulary_machine_name' => 'flavours',
  );
  $terms[] = array(
    'name' => 'Stuffed',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'adfb3974-b099-442e-80a0-03e6d4047f71',
    'vocabulary_machine_name' => 'bala_type',
  );
  $terms[] = array(
    'name' => 'Stuffed Bombom',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'bc26b767-78b2-4d48-8770-6fb357439518',
    'vocabulary_machine_name' => 'bala_type',
  );
  $terms[] = array(
    'name' => 'Morango',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'cd9c0bdc-d850-4658-8440-02169a7daaaa',
    'vocabulary_machine_name' => 'flavours',
  );
  $terms[] = array(
    'name' => 'Bala de Coco',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'cf072ebd-c083-4b07-90be-0b6ec5b939c7',
    'vocabulary_machine_name' => 'product_type',
  );
  $terms[] = array(
    'name' => 'Maracujá',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'e4550f71-9106-47c8-b54d-b97406670517',
    'vocabulary_machine_name' => 'flavours',
  );
  return $terms;
}
